spring:
    thymeleaf:
        prefix : classpath:templates/
        suffix : .html

# @ConfigurationProperty
application.jwt.secretKey: "secretsecretsecretsecretsecretsecretsecretsecretsecret"
application.jwt.tokenPrefix: "Bearer "
application.jwt.tokenExpirationAfterDays: 1